### ISSUE TITLE
Hitsplats show through open interfaces

### ISSUE THREAD

**Issue by FourWolves** [Extended-Hitsplats/extended-hitsplats#7]
Hitsplats show through the bank interface (team prepotting while I was in my bank is how I saw this)

**Comment by Ferrariic** [comment]
> Hitsplats show through the bank interface (team prepotting while I was in my bank is how I saw this)

Hey there,  the overlay needs to be rectified. I'll find time for this and fix it.

**Comment by YeahImRose** [comment]
Fixed as of 2dac10fc94d7cf8ee69e238421fd440dae91dfe7
